server:
  port: 8083
  servlet:
    context-path: /market

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: artemis-gate
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=artemis-test
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
